# -*- coding: utf-8 -*-
"""RESTapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZNuY6VdtssH-9NSC9JyvsIEhME352JcM
"""

from flask import Flask,request
import pandas as pd
import numpy as np
import torch
import math
from sentence_transformers import SentenceTransformer,util
model = torch.load('C:\Users\Pooja Kumari\.spyder\best_model_similarity.pth')
app=Flask(__name__)

@app.route('/predict')

def prediction():
    sentence1=request.args.get('string1')
    sentence2=request.args.get('string2')
    prediction=model.encode([sentence1,sentence2])
    cosine_scores = util.pytorch_cos_sim(prediction[0],prediction[1])
    
    return "similarity score is " + str(cosine_scores)

if __name__=='__main__':
    app.run()

